behaviors:
  Gatherer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      sequence_length: 64
      memory_size: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.03
        encoding_size: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 128
    summary_freq: 50000
    threaded: true
environment_parameters:
  Gatherer:
    curriculum:
      - name: MyFirstLesson
        completion_criteria:
          measure: reward
          behavior: Gatherer
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 20.0
        value: 0.0
      - name: MySecondLesson
        completion_criteria:
          measure: reward
          behavior: Gatherer
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 30.0
        value: 1.0
      - name: MyThirdLesson
        completion_criteria:
          measure: reward
          behavior: Gatherer
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 45.0
        value: 2.0
      - name: MyfourthLesson
        completion_criteria:
          measure: reward
          behavior: Gatherer
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 70.0
        value: 3.0
      - name: MyLastLesson
        completion_criteria:
          measure: reward
          behavior: Gatherer
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 85.0
        value: 4.0